### ISSUE TITLE
FIXME Accomodate for edge cases in `parse_mod_data` for mods that have no/missing local metadata

### ISSUE THREAD

**Issue by llyarden** [oceancabbage/RimSort#38]
- [x] Populate stub ["name"] field & create additional check in Dynamic Query 
- [x]  Create new 'invalid' tag for mods that are invalid to factor for contextMenu deletion of these mods
- [x] Factor 'invalid' tag for `QLabel` styles associated with mod
- [x] Populate `invalid_mods` with the aforementioned tag, as well as stub metadata to indicate to the user these items can be cleaned up

I have absolutely no clue what has caused this to happen, but there's a mod on the workshop with no name in its About.xml.  Which causes some unusual effects - searching the mod list it's in causes RimSort to crash, as does trying to activate it.  If you activate it manually by adding its package id to ModsConfig.xml, RimSort crashes on startup.  You can, however, click on it if you find it in the modlist and it displays just fine!  Just ignore my nonsense list of active mods, I was getting them out the way for the screenshot and confirmation that this mod was the cause of the crashes.

![ModWithNoName](https://user-images.githubusercontent.com/57965302/221362971-ebed8856-b3b2-4876-92d3-65923060486e.png)

(To be fair, Rimworld itself also has no idea how to handle this and doesn't even show it in the in-game list of mods, and if you manually force it to be active by adding it to ModsConfig.xml it shows up weirdly in the active list as 'Workshop Mod [number]' but still with the option to enable it, and you can't drag it to the inactive list.  I didn't bother trying to actually start a game with it 'active.')

Link to the mod itself: https://steamcommunity.com/sharedfiles/filedetails/?id=2558484114 (and yes I've unsubscribed and resubscribed and all the usual stuff.)

I've cut out the logs that were specific to every other mod here, I figured they probably weren't relevant.

```[INFO][2023-02-25 14:17:55,474][8860][__main__][<module>][28] : Starting RimSort application
[INFO][2023-02-25 14:17:55,493][8860][__main__][<module>][99] : Setting application styles
[INFO][2023-02-25 14:17:55,494][8860][__main__][__init__][56] : Starting MainWindow initialization
[INFO][2023-02-25 14:17:55,495][8860][__main__][__init__][69] : Start creating main panels
[INFO][2023-02-25 14:17:55,495][8860][view.game_configuration_panel][__init__][41] : Starting GameConfiguration initialization
[INFO][2023-02-25 14:17:5
5,517][8860][view.game_configuration_panel][initialize_settings_panel][389] : Calling Settings Panel initialization
[INFO][2023-02-25 14:17:55,518][8860][panel.settings_panel][__init__][15] : Starting SettingsPanel initialization
[INFO][2023-02-25 14:17:55,519][8860][panel.settings_panel][__init__][47] : Finished SettingsPanel initialization
[INFO][2023-02-25 14:17:55,519][8860][view.game_configuration_panel][initialize_storage][305] : Starting storage initialization
[INFO][2023-02-25 14:17:55,519][8860][view.game_configuration_panel][initialize_storage][309] : Determined storage path: C:/Users/{removing my username from the logs}/AppData/Local/RimSort
[INFO][2023-02-25 14:17:55,520][8860][view.game_configuration_panel][initialize_storage][321] : Determined settings file path: C:/Users/{removing my username from the logs}/AppData/Local/RimSort\settings.json
[INFO][2023-02-25 14:17:55,520][8860][view.game_configuration_panel][initialize_storage][332] : Settings file [C:/Users/{removing my username from the logs}/AppData/Local/RimSort\settings.json] exists. Opening file
[INFO][2023-02-25 14:17:55,520][8860][view.game_configuration_panel][initialize_storage][334] : Loading JSON from file
[INFO][2023-02-25 14:17:55,520][8860][view.game_configuration_panel][initialize_storage][336] : JSON has been loaded: {'game_folder': 'C:\\Program Files (x86)\\Steam\\steamapps\\common\\Rimworld', 'config_folder': 'C:\\Users\\{removing my username from the logs}\\AppData\\LocalLow\\Ludeon Studios\\RimWorld by Ludeon Studios\\Config', 'workshop_folder': 'C:\\Program Files (x86)\\Steam\\steamapps\\workshop\\content\\294100', 'local_folder': 'C:\\Program Files (x86)\\Steam\\steamapps\\common\\Rimworld\\Mods'}
[INFO][2023-02-25 14:17:55,520][8860][view.game_configuration_panel][initialize_storage][337] : Setting relevant QLineEdits now
[INFO][2023-02-25 14:17:55,666][8860][view.game_configuration_panel][initialize_storage][378] : Finished storage initialization
[INFO][2023-02-25 14:17:55,666][8860][view.game_configuration_panel][__init__][255] : Finished GameConfiguration initialization
[INFO][2023-02-25 14:17:55,666][8860][view.main_content_panel][__init__][41] : Starting MainContent initialization
[INFO][2023-02-25 14:17:55,666][8860][view.main_content_panel][__init__][56] : Instantiating MainContent QWidget subclasses
[INFO][2023-02-25 14:17:55,666][8860][sub_view.mod_info_panel][__init__][24] : Starting ModInfo initialization
[INFO][2023-02-25 14:17:55,666][8860][model.scroll_label][__init__][21] : Starting ScrollLabel initialization
[INFO][2023-02-25 14:17:55,667][8860][model.scroll_label][__init__][52] : Finished ScrollLabel initialization
[INFO][2023-02-25 14:17:55,667][8860][sub_view.mod_info_panel][__init__][83] : Finished ModInfo initialization
[INFO][2023-02-25 14:17:55,667][8860][sub_view.active_mods_panel][__init__][25] : Starting ActiveModList initialization
[INFO][2023-02-25 14:17:55,667][8860][model.mod_list][__init__][32] : Starting ModListWidget initialization
[INFO][2023-02-25 14:17:55,669][8860][model.mod_list][__init__][72] : Finished ModListWidget initialization
[INFO][2023-02-25 14:17:55,685][8860][sub_view.active_mods_panel][__init__][105] : Finished ActiveModList initialization
[INFO][2023-02-25 14:17:55,685][8860][sub_view.inactive_mods_panel][__init__][25] : Starting InactiveModList initialization
[INFO][2023-02-25 14:17:55,685][8860][model.mod_list][__init__][32] : Starting ModListWidget initialization
[INFO][2023-02-25 14:17:55,686][8860][model.mod_list][__init__][72] : Finished ModListWidget initialization
[INFO][2023-02-25 14:17:55,686][8860][sub_view.inactive_mods_panel][__init__][62] : Finished InactiveModList initialization
[INFO][2023-02-25 14:17:55,686][8860][sub_view.actions_panel][__init__][26] : Starting Actions initialization
[INFO][2023-02-25 14:17:55,687][8860][sub_view.actions_panel][__init__][89] : Finished Actions initialization
[INFO][2023-02-25 14:17:55,687][8860][view.main_content_panel][__init__][61] : Finished instantiating MainContent QWidget subclasses
[INFO][2023-02-25 14:17:55,688][8860][view.main_content_panel][__init__][81] : Loading GameConfiguration instance
[INFO][2023-02-25 14:17:55,688][8860][view.game_configuration_panel][check_if_essential_paths_are_set][268] : Checking if essential paths are set
[INFO][2023-02-25 14:17:55,688][8860][view.game_configuration_panel][get_game_folder_path][747] : Responding with requested Game Folder: C:\Program Files (x86)\Steam\steamapps\common\Rimworld
[INFO][2023-02-25 14:17:55,688][8860][view.game_configuration_panel][get_config_folder_path][753] : Responding with requested Config Folder: C:\Users\{removing my username from the logs}\AppData\LocalLow\Ludeon Studios\RimWorld by Ludeon Studios\Config
[INFO][2023-02-25 14:17:55,688][8860][view.game_configuration_panel][check_if_essential_paths_are_set][295] : Paths have been set and exist, returning True
[INFO][2023-02-25 14:17:55,688][8860][view.main_content_panel][refresh_cache_calculations][129] : Refreshing cache calculations
[INFO][2023-02-25 14:17:55,688][8860][view.game_configuration_panel][get_game_folder_path][747] : Responding with requested Game Folder: C:\Program Files (x86)\Steam\steamapps\common\Rimworld
[INFO][2023-02-25 14:17:55,688][8860][util.mods][get_game_version][922] : Getting game version from Game Folder: C:\Program Files (x86)\Steam\steamapps\common\Rimworld
[INFO][2023-02-25 14:17:55,756][8860][util.mods][get_game_version][928] : Generated Version.txt path: C:\Program Files (x86)\Steam\steamapps\common\Rimworld\Version.txt
[INFO][2023-02-25 14:17:55,757][8860][util.mods][get_game_version][930] : Version.txt path exists
[INFO][2023-02-25 14:17:55,757][8860][util.mods][get_game_version][933] : Retrieved game version from Version.txt: 1.4.3641 rev649
[INFO][2023-02-25 14:17:55,757][8860][util.mods][get_game_version][946] : Finished getting game version from Game Folder, returning now: 1.4.3641 rev649
[INFO][2023-02-25 14:17:55,758][8860][view.game_configuration_panel][get_game_folder_path][747] : Responding with requested Game Folder: C:\Program Files (x86)\Steam\steamapps\common\Rimworld
[INFO][2023-02-25 14:17:55,758][8860][util.mods][get_installed_expansions][200] : Getting installed expansions with Game Folder path: C:\Program Files (x86)\Steam\steamapps\common\Rimworld
[INFO][2023-02-25 14:17:55,758][8860][util.mods][get_installed_expansions][209] : Attempting to get BASE/EXPANSIONS data from Rimworld's /Data folder: C:\Program Files (x86)\Steam\steamapps\common\Rimworld\Data
[INFO][2023-02-25 14:17:55,758][8860][util.mods][parse_mod_data][71] : Starting parsing mod data for intent: game install

(starts getting expansions and mods)

[INFO][2023-02-25 14:17:56,353][8860][util.xml][xml_path_to_json][21] : Parsing XML file at: C:\Program Files (x86)\Steam\steamapps\workshop\content\294100\2558484114\About\About.xml
[DEBUG][2023-02-25 14:17:56,353][8860][util.xml][xml_path_to_json][24] : XML file parsed with the following data: {'ModMetaData': {'packageId': 'Minecart.Archotech.Med', 'author': 'MinecartRider', 'supportedVersions': {'li': '1.3'}, 'loadAfter': {'li': 'Ludeon.RimWorld'}, 'description': 'A light mod that adds archotech medicine and dealbreaker, a drug that can counteract the effects of luciferium.\n    Also provides normal and bulk crafting recipe for glitterworld medicine, luciferium, neutroamine, and normal medicine, as well as crafting recipes for mech serums.'}}
[DEBUG][2023-02-25 14:17:56,354][8860][util.mods][parse_mod_data][141] : Attempting to normalize XML content keys
[DEBUG][2023-02-25 14:17:56,354][8860][util.mods][parse_mod_data][143] : Normalized XML content: {'modmetadata': {'packageId': 'Minecart.Archotech.Med', 'author': 'MinecartRider', 'supportedVersions': {'li': '1.3'}, 'loadAfter': {'li': 'Ludeon.RimWorld'}, 'description': 'A light mod that adds archotech medicine and dealbreaker, a drug that can counteract the effects of luciferium.\n    Also provides normal and bulk crafting recipe for glitterworld medicine, luciferium, neutroamine, and normal medicine, as well as crafting recipes for mech serums.'}}
[DEBUG][2023-02-25 14:17:56,354][8860][util.mods][parse_mod_data][144] : Editing XML content
[DEBUG][2023-02-25 14:17:56,354][8860][util.mods][parse_mod_data][155] : Finished editing XML content, adding final content to larger list: {'packageId': 'minecart.archotech.med', 'author': 'MinecartRider', 'supportedVersions': {'li': '1.3'}, 'loadAfter': {'li': 'Ludeon.RimWorld'}, 'description': 'A light mod that adds archotech medicine and dealbreaker, a drug that can counteract the effects of luciferium.\n    Also provides normal and bulk crafting recipe for glitterworld medicine, luciferium, neutroamine, and normal medicine, as well as crafting recipes for mech serums.', 'folder': '2558484114', 'path': 'C:\\Program Files (x86)\\Steam\\steamapps\\workshop\\content\\294100\\2558484114'}

(continues getting expansions and mods)

[INFO][2023-02-25 14:17:57,225][8860][util.mods][get_dependencies_for_mods][658] : Finished adding dependencies through Community Rules
[INFO][2023-02-25 14:17:57,225][8860][util.mods][get_dependencies_for_mods][659] : Total number of loadTheseBefore rules: 1788
[INFO][2023-02-25 14:17:57,225][8860][util.mods][get_dependencies_for_mods][662] : Total number of loadTheseAfter rules: 1788
[INFO][2023-02-25 14:17:57,225][8860][util.mods][get_dependencies_for_mods][665] : Total number of dependencies: 952
[INFO][2023-02-25 14:17:57,225][8860][util.mods][get_dependencies_for_mods][668] : Total number of incompatibilities: 15
[INFO][2023-02-25 14:17:57,225][8860][util.mods][get_dependencies_for_mods][671] : Returing all mods now
[INFO][2023-02-25 14:17:57,226][8860][view.main_content_panel][refresh_cache_calculations][199] : Finished refreshing cache calculations
[INFO][2023-02-25 14:17:57,226][8860][view.main_content_panel][repopulate_lists][209] : Repopulating mod lists
[INFO][2023-02-25 14:17:57,226][8860][view.game_configuration_panel][get_config_path][759] : Getting path to ModsConfig.xml
[INFO][2023-02-25 14:17:57,226][8860][view.game_configuration_panel][get_config_folder_path][753] : Responding with requested Config Folder: C:\Users\{removing my username from the logs}\AppData\LocalLow\Ludeon Studios\RimWorld by Ludeon Studios\Config
[INFO][2023-02-25 14:17:57,226][8860][view.game_configuration_panel][get_config_path][763] : Determined ModsConfig.xml path: C:\Users\{removing my username from the logs}\AppData\LocalLow\Ludeon Studios\RimWorld by Ludeon Studios\Config\ModsConfig.xml
[INFO][2023-02-25 14:17:57,226][8860][util.mods][get_active_inactive_mods][30] : Starting generating active and inactive mods
[INFO][2023-02-25 14:17:57,226][8860][util.mods][get_active_inactive_mods][33] : Calling get active mods with Config Path: C:\Users\{removing my username from the logs}\AppData\LocalLow\Ludeon Studios\RimWorld by Ludeon Studios\Config\ModsConfig.xml
[INFO][2023-02-25 14:17:57,226][8860][util.mods][get_active_mods_from_config][960] : Getting active mods with Config Path: C:\Users\{removing my username from the logs}\AppData\LocalLow\Ludeon Studios\RimWorld by Ludeon Studios\Config\ModsConfig.xml
[INFO][2023-02-25 14:17:57,227][8860][util.xml][xml_path_to_json][21] : Parsing XML file at: C:\Users\{removing my username from the logs}\AppData\LocalLow\Ludeon Studios\RimWorld by Ludeon Studios\Config\ModsConfig.xml
[DEBUG][2023-02-25 14:17:57,227][8860][util.xml][xml_path_to_json][24] : XML file parsed with the following data: {'ModsConfigData': {'version': '1.4.3641 rev649', 'activeMods': {'li': ['ludeon.rimworld', 'ludeon.rimworld.royalty', 'ludeon.rimworld.ideology', 'ludeon.rimworld.biotech']}, 'knownExpansions': {'li': ['ludeon.rimworld.royalty', 'ludeon.rimworld.ideology', 'ludeon.rimworld.biotech']}}}
[INFO][2023-02-25 14:17:57,227][8860][util.schema][validate_mods_config_format][13] : Validating mods config: {'ModsConfigData': {'version': '1.4.3641 rev649', 'activeMods': {'li': ['ludeon.rimworld', 'ludeon.rimworld.royalty', 'ludeon.rimworld.ideology', 'ludeon.rimworld.biotech']}, 'knownExpansions': {'li': ['ludeon.rimworld.royalty', 'ludeon.rimworld.ideology', 'ludeon.rimworld.biotech']}}}
[INFO][2023-02-25 14:17:57,227][8860][util.schema][validate_mods_config_format][18] : ModsConfig.xml is properly formatted
[INFO][2023-02-25 14:17:57,227][8860][util.mods][get_active_mods_from_config][966] : Returning empty active mods dict with 4 entries
[INFO][2023-02-25 14:17:57,227][8860][util.mods][get_active_inactive_mods][36] : Calling populate active mods with data
[INFO][2023-02-25 14:17:57,227][8860][util.mods][populate_active_mods_workshop_data][988] : Populating empty active mods with data
[INFO][2023-02-25 14:17:57,227][8860][util.mods][populate_active_mods_workshop_data][1004] : Finished populating empty active mods with data
[INFO][2023-02-25 14:17:57,227][8860][util.mods][get_active_inactive_mods][61] : Calling get inactive mods
[INFO][2023-02-25 14:17:57,227][8860][util.mods][get_inactive_mods][1033] : Generating inactive mod lists from subtracting all mods with active mods
[INFO][2023-02-25 14:17:57,227][8860][util.mods][get_inactive_mods][1041] : Finished generating inactive mods list
[INFO][2023-02-25 14:17:57,227][8860][util.mods][get_active_inactive_mods][64] : Returning newly generated active mods [4] and inactive mods [926] list
[INFO][2023-02-25 14:17:57,227][8860][view.main_content_panel][repopulate_lists][215] : Populating mod list data for the first time, so cache it for the restore function
[INFO][2023-02-25 14:17:57,227][8860][view.main_content_panel][_insert_data_into_lists][401] : Inserting mod data into active [4] and inactive [926] mod lists
[INFO][2023-02-25 14:17:57,228][8860][model.mod_list][recreate_mod_list][80] : Internally recreating mod list
[INFO][2023-02-25 14:17:57,228][8860][model.mod_list][recreate_mod_list][80] : Internally recreating mod list
[INFO][2023-02-25 14:17:57,246][8860][view.main_content_panel][_insert_data_into_lists][407] : Finished inserting mod data into active [4] and inactive [926] mod lists
[INFO][2023-02-25 14:17:57,246][8860][view.main_content_panel][__init__][98] : Finished MainContent initialization
[INFO][2023-02-25 14:17:57,246][8860][view.status_panel][__init__][23] : Starting Status initialization
[INFO][2023-02-25 14:17:57,246][8860][view.status_panel][__init__][42] : Finished Status initialization
[INFO][2023-02-25 14:17:57,246][8860][__main__][__init__][73] : Finished creating main panels
[INFO][2023-02-25 14:17:57,246][8860][__main__][__init__][78] : Connecting MainWindow signals and slots
[INFO][2023-02-25 14:17:57,253][8860][__main__][__init__][93] : Finished MainWindow initialization
[INFO][2023-02-25 14:17:57,253][8860][__main__][<module>][105] : Showing MainWindow
[INFO][2023-02-25 14:17:57,327][8860][sub_view.active_mods_panel][handle_internal_mod_list_updated][344] : Active mod count changed to: 4
[INFO][2023-02-25 14:17:57,328][8860][sub_view.active_mods_panel][recalculate_internal_list_errors][116] : Recalculating internal list errors
[INFO][2023-02-25 14:17:57,328][8860][model.mod_list][get_list_items_by_dict][144] : Returning a list of all mod items by json data
[INFO][2023-02-25 14:17:57,328][8860][model.mod_list][get_list_items_by_dict][152] : Collected json data for 1 mods
[INFO][2023-02-25 14:17:57,328][8860][sub_view.active_mods_panel][recalculate_internal_list_errors][338] : Finished recalculating internal list errors
[INFO][2023-02-25 14:17:57,330][8860][sub_view.active_mods_panel][handle_internal_mod_list_updated][344] : Active mod count changed to: 4
[INFO][2023-02-25 14:17:57,331][8860][sub_view.active_mods_panel][recalculate_internal_list_errors][116] : Recalculating internal list errors
[INFO][2023-02-25 14:17:57,331][8860][model.mod_list][get_list_items_by_dict][144] : Returning a list of all mod items by json data
[INFO][2023-02-25 14:17:57,331][8860][model.mod_list][get_list_items_by_dict][152] : Collected json data for 2 mods
[INFO][2023-02-25 14:17:57,331][8860][sub_view.active_mods_panel][recalculate_internal_list_errors][338] : Finished recalculating internal list errors
[INFO][2023-02-25 14:17:57,333][8860][sub_view.active_mods_panel][handle_internal_mod_list_updated][344] : Active mod count changed to: 4
[INFO][2023-02-25 14:17:57,334][8860][sub_view.active_mods_panel][recalculate_internal_list_errors][116] : Recalculating internal list errors
[INFO][2023-02-25 14:17:57,334][8860][model.mod_list][get_list_items_by_dict][144] : Returning a list of all mod items by json data
[INFO][2023-02-25 14:17:57,334][8860][model.mod_list][get_list_items_by_dict][152] : Collected json data for 3 mods
[INFO][2023-02-25 14:17:57,334][8860][sub_view.active_mods_panel][recalculate_internal_list_errors][338] : Finished recalculating internal list errors
[INFO][2023-02-25 14:17:57,335][8860][sub_view.active_mods_panel][handle_internal_mod_list_updated][344] : Active mod count changed to: 4
[INFO][2023-02-25 14:17:57,336][8860][sub_view.active_mods_panel][recalculate_internal_list_errors][116] : Recalculating internal list errors
[INFO][2023-02-25 14:17:57,336][8860][model.mod_list][get_list_items_by_dict][144] : Returning a list of all mod items by json data
[INFO][2023-02-25 14:17:57,336][8860][model.mod_list][get_list_items_by_dict][152] : Collected json data for 4 mods
[INFO][2023-02-25 14:17:57,336][8860][sub_view.active_mods_panel][recalculate_internal_list_errors][338] : Finished recalculating internal list errors
[INFO][2023-02-25 14:17:57,340][8860][sub_view.inactive_mods_panel][change_mod_num_display][66] : Inactive mod count changed to: 926
[INFO][2023-02-25 14:17:57,345][8860][sub_view.inactive_mods_panel][change_mod_num_display][66] : Inactive mod count changed to: 926

(another two hundred odd of the same line)

[INFO][2023-02-25 14:18:05,491][8860][sub_view.inactive_mods_panel][change_mod_num_display][66] : Inactive mod count changed to: 926
[INFO][2023-02-25 14:18:05,504][8860][sub_view.inactive_mods_panel][change_mod_num_display][66] : Inactive mod count changed to: 926
[INFO][2023-02-25 14:18:05,518][8860][sub_view.inactive_mods_panel][change_mod_num_display][66] : Inactive mod count changed to: 926
[INFO][2023-02-25 14:18:05,530][8860][sub_view.inactive_mods_panel][change_mod_num_display][66] : Inactive mod count changed to: 926
[INFO][2023-02-25 14:18:05,544][8860][sub_view.inactive_mods_panel][change_mod_num_display][66] : Inactive mod count changed to: 926
[ERROR][2023-02-25 14:18:08,520][8860][__main__][handle_exception][37] : Main application loop has failed with an uncaught exception
Traceback (most recent call last):
  File "sub_view\inactive_mods_panel.py", line 79, in signal_inactive_mods_search
KeyError: 'name'
[INFO][2023-02-25 14:18:08,521][8860][util.error][show_fatal_error][100] : Showing fatal error box with input: [None], [None], [Traceback (most recent call last):
  File "sub_view\inactive_mods_panel.py", line 79, in signal_inactive_mods_search
KeyError: 'name'
]
[INFO][2023-02-25 14:18:08,523][8860][util.error][show_fatal_error][125] : Finished showing fatal error box```

**Comment by oceancabbage** [comment]
@llyarden this is great info! Sorry it took so long to get back to you. This is definitely something I hadn't anticipated, I'm coming to learn that you really can't rely on mod authors to follow rules for `About.xml`s. I can definitely add some checks for this, but I think I need your input on what the behavior _should_ be. If RimWorld itself doesn't even show the mod and it takes forcefully inserting the mod into `ModsConfig.xml` in order for it to show, should RimSort just ignore mods with no `name`? Or do we want to add support for these mods, and in RimSort we'll just give it a placeholder name?

**Comment by llyarden** [comment]
Personally I would suggest simply ignoring the mod in its entirety, the same way Rimworld does.  I don't know if the mod would even work without a name, Rimworld's inbuilt mod manager certainly seemed confused about whether it was active when I forced it in.  (I probably should've tested that, sorry.)

Or maybe let it show up in the inactive mod list and just have some sort of error pop up on the preview or when you try to drag it across saying something like 'this mod has no `name` parameter in its `About.xml`, please report this to the mod author.'  Just in case people start wondering why a mod they've subscribed to doesn't show up in RimSort.

**Comment by twstagg** [comment]
@oceancabbage here is another edge case:

[10:57 AM]Cousax: I don't know if this is good or bad: RimSort does not show "remnant mod folders" (The ones left behind when you unsubscribe from a mod, but you had custom/extra files in there, so they don't get deleted by steam; .dds files, extra reference images and some PSDs in my case) 

![image](https://user-images.githubusercontent.com/2766946/224119364-2d4fc522-0415-4ea7-a0aa-5023057b60e4.png)

I think that a proper solution to both of these issues is to treat a folder that has missing/no metadata as an UNKNOWN similar to RimPy

**Comment by oceancabbage** [comment]
@twstagg the case you just mentioned is actually caught by RimSort and logged as a warning. Those folders are ignored and not displayed and I think it should stay that way (i.e. we shouldn't do what RimPy is doing).

**Comment by twstagg** [comment]
Fixed in sprint-a1.0.3 3519d39
