### ISSUE TITLE
FIXME: Fatal Error on start up Alpha v1.0.3-RC2

### ISSUE THREAD

**Issue by MadAmbassador** [oceancabbage/RimSort#58]
Accidentally caused a fatal error when switching to Rimsort Dynamic Query on Alpha v1.0.3-RC2 Darwin. The problem seems to persist through a fresh install.
--------------------------------------
**Stack Trace:**

Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 692, in urlopen
  File "urllib3/connectionpool.py", line 281, in _get_conn
  File "urllib3/connectionpool.py", line 1011, in _new_conn
urllib3.exceptions.SSLError: Can't connect to HTTPS URL because the SSL module is not available.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests/adapters.py", line 489, in send
  File "urllib3/connectionpool.py", line 787, in urlopen
  File "urllib3/util/retry.py", line 592, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.steampowered.com', port=443): Max retries exceeded with url: /ISteamWebAPIUtil/GetSupportedAPIList/v1/?format=json&key= (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available."))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "RimSort.py", line 127, in <module>
  File "RimSort.py", line 93, in __init__
  File "view/main_content_panel.py", line 140, in __init__
  File "view/main_content_panel.py", line 289, in refresh_cache_calculations
  File "util/mods.py", line 674, in get_3rd_party_metadata
  File "util/steam/webapi/wrapper.py", line 189, in __init__
  File "steam/webapi.py", line 106, in __init__
  File "steam/webapi.py", line 123, in fetch_interfaces
  File "steam/webapi.py", line 468, in get
  File "steam/webapi.py", line 426, in webapi_request
  File "requests/sessions.py", line 600, in get
  File "requests/sessions.py", line 587, in request
  File "requests/sessions.py", line 701, in send
  File "requests/adapters.py", line 563, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.steampowered.com', port=443): Max retries exceeded with url: /ISteamWebAPIUtil/GetSupportedAPIList/v1/?format=json&key= (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available."))

**Log File:**

**Comment by twstagg** [comment]
Hey there. Thanks for the report. I am currently looking at moving over to Nuitka from PyInstaller. Please stay tuned! This issue should be resolved with that

**Comment by twstagg** [comment]
Should be fixed in a1.0.3-RC3

Please test release when you can
